balatro_enum!(Spectral {
    Familiar = "c_familiar",
    Grim = "c_grim",
    Incantation = "c_incantation",
    Talisman = "c_talisman",
    Aura = "c_aura",
    Wraith = "c_wraith",
    Sigil = "c_sigil",
    Ouija = "c_ouija",
    Ectoplasm = "c_ectoplasm",
    Immolate = "c_immolate",
    Ankh = "c_ankh",
    DejaVu = "c_deja_vu",
    Hex = "c_hex",
    Trance = "c_trance",
    Medium = "c_medium",
    Cryptid = "c_cryptid",
    TheSoul = "c_soul",
    BlackHole = "c_black_hole",
});
