use crate::balatro_enum;
balatro_enum!(Tarot {
    Fool = "c_fool",
    Magician = "c_magician",
    HighPriestess = "c_high_priestess",
    Empress = "c_empress",
    Emperor = "c_emperor",
    Heirophant = "c_heirophant",
    Lovers = "c_lovers",
    Chariot = "c_chariot",
    Justice = "c_justice",
    Hermit = "c_hermit",
    WheelOfFortune = "c_wheel_of_fortune",
    Strength = "c_strength",
    HangedMan = "c_hanged_man",
    Death = "c_death",
    Temperance = "c_temperance",
    Devil = "c_devil",
    Tower = "c_tower",
    Star = "c_star",
    Moon = "c_moon",
    Sun = "c_sun",
    Judgement = "c_judgement",
    World = "c_world",
});
